version: 2
jobs:
  build:
    working_directory: ~/javascript-ioc-library
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
