version: 2
jobs:
  build:
    working_directory: ~/javascript-ioc-library
    docker:
      - image: circleci/node:6.2.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
